spring.application.name=mini-acquiring

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_acquiring
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false