CREATE SCHEMA IF NOT EXISTS core;

CREATE  TABLE IF NOT EXISTS core.merchant ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	commission_value     numeric(38,2)  NOT NULL  ,
	name                 text  NOT NULL  ,
	commission_type      bigint  NOT NULL  ,
	status               bigint    ,
	CONSTRAINT pk_merchant PRIMARY KEY ( id )
 );

CREATE  TABLE IF NOT EXISTS core."operation" ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	created_at           timestamp DEFAULT CURRENT_TIMESTAMP   ,
	parent_id            bigint    ,
	processed_at         timestamp    ,
	"sum"                numeric(38,2)  NOT NULL  ,
	merchant_id          bigint  NOT NULL  ,
	status_id            bigint  NOT NULL  ,
	operation_type_id    bigint  NOT NULL  ,
	CONSTRAINT pk_operati PRIMARY KEY ( id )
 );

CREATE INDEX idx_operation_merchant_id ON core."operation"  ( merchant_id );

CREATE INDEX idx_operation_status_id ON core."operation"  ( status_id );

CREATE  TABLE IF NOT EXISTS core.commission ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	processed_at         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	total_commission     numeric(38,2)  NOT NULL  ,
	operation_id         bigint  NOT NULL  ,
	CONSTRAINT pk_commission PRIMARY KEY ( id )
 );

CREATE INDEX idx_commission_operation_id ON core.commission  ( operation_id );

ALTER TABLE core.commission ADD CONSTRAINT fk_commission_merchant FOREIGN KEY ( operation_id ) REFERENCES core."operation"( id );

ALTER TABLE core."operation" ADD CONSTRAINT fk_operation_merchant FOREIGN KEY ( merchant_id ) REFERENCES core.merchant( id );

CREATE SCHEMA IF NOT EXISTS status;

CREATE  TABLE IF NOT EXISTS status.merchant_status ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name                 varchar(255)  NOT NULL  ,
	code                 varchar(50)  NOT NULL  ,
	CONSTRAINT pk_merchant_status PRIMARY KEY ( id ),
	CONSTRAINT unq_merchant_status UNIQUE ( name ) ,
	CONSTRAINT unq_merchant_status_0 UNIQUE ( code ) 
 );

CREATE  TABLE IF NOT EXISTS status.operation_status ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name                 varchar(255)  NOT NULL  ,
	code                 varchar(50)  NOT NULL  ,
	CONSTRAINT pk_operation_status PRIMARY KEY ( id ),
	CONSTRAINT unq_operation_status UNIQUE ( name ) ,
	CONSTRAINT unq_operation_status_0 UNIQUE ( code ) 
 );

CREATE SCHEMA IF NOT EXISTS "type";

CREATE  TABLE IF NOT EXISTS "type".commission_type ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name                 varchar(255)  NOT NULL  ,
	code                 varchar(50)  NOT NULL  ,
	CONSTRAINT pk_commission_type PRIMARY KEY ( id ),
	CONSTRAINT unq_commission_type UNIQUE ( name ) ,
	CONSTRAINT unq_commission_type_0 UNIQUE ( code ) 
 );

CREATE  TABLE IF NOT EXISTS "type".operation_type ( 
	id                   bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name                 varchar(255)  NOT NULL  ,
	code                 varchar(50)    ,
	CONSTRAINT pk_operation_type PRIMARY KEY ( id ),
	CONSTRAINT unq_operation_type UNIQUE ( name ) ,
	CONSTRAINT unq_operation_type_0 UNIQUE ( code ) 
 );

ALTER TABLE core.merchant ADD CONSTRAINT fk_merchant_merchant_status FOREIGN KEY ( status ) REFERENCES status.merchant_status( id );

ALTER TABLE core.merchant ADD CONSTRAINT fk_merchant_commission_type FOREIGN KEY ( commission_type ) REFERENCES "type".commission_type( id );

ALTER TABLE core."operation" ADD CONSTRAINT fk_operation_operation_status FOREIGN KEY ( status_id ) REFERENCES status.operation_status( id );

ALTER TABLE core."operation" ADD CONSTRAINT fk_operation_operation_type FOREIGN KEY ( operation_type_id ) REFERENCES "type".operation_type( id );

